baseURL = 'https://tabulate.tech/'
languageCode = 'en-us'
title = 'Tabulate'
pluralizeListTitles = false

[params]
statusOrder = ["success", "info", "warning", "danger"]

[params.author]
name = 'Connor Sample'

[markup.highlight]
lineNos = true

[minify]
minifyOutput = true
