baseURL = 'https://tabulate.tech/'
languageCode = 'en-us'
title = 'Tabulate'
pluralizeListTitles = false

[params]
statusOrder = ["success", "info", "warning", "danger"]

[params.author]
name = 'Connor Sample'

[markup.highlight]
lineNos = true
style = "catppuccin-mocha"

[minify]
minifyOutput = true

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\[', '\]']]
inline = [['\(', '\)']]

[build]
[build.buildStats]
enable = true

[module]
# default
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "static"

# KaTeX
[[module.mounts]]
source = "node_modules/katex/dist/katex.min.css"
target = "assets/katex/katex.min.css"
[[module.mounts]]
source = "node_modules/katex/dist/fonts"
target = "static/katex/fonts"

# Font Awesome
[[module.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"
